### PR TITLE
fix depwarns under 0.7 and bump REQUIRE and CI to 0.6

### PR DESCRIPTION
**Pull request by Sacha0**
Best! :)

### CODE REVIEW

**Comment by CarloLucibello** [comment]
bump? @stevengj

**Comment by stevengj** [comment]
Thanks for the reminder.  I'm fine with requiring 0.6 now.

**Comment by Sacha0** [comment]
Thanks all! :)

**Comment by stevengj** [comment]
Tagged in https://github.com/JuliaLang/METADATA.jl/pull/11553

**Pull request merged**
